version: '3.8'

services:
  backend:
    build: backend/
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    
  frontend:
    build: frontend/
    ports: 
      - 5173:5173
    depends_on:
      - backend
