# Generated by Django 4.1.1 on 2022-09-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("create_session", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="created_in",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="updated_in",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="musclegroup",
            old_name="created_in",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="musclegroup",
            old_name="updated_in",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="serie",
            old_name="created_in",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="serie",
            old_name="updated_in",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="created_in",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="updated_in",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="training",
            old_name="created_in",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="training",
            old_name="updated_in",
            new_name="updated_at",
        ),
    ]
